### ISSUE TITLE
Make rough draft of survey questions.

### ISSUE THREAD

**Issue by Justin-Tomasina** [Justin-Tomasina/QMB-210-5-group-3#1]
This is for Ronan, Alessio, and Cooper.
Follow the guide on canvas in the "group project requirements" pdf

**Comment by ronanflanny** [comment]
1. The first three questions I'm thinking the following:

- What year are you?
- Do you have a meal plan?
- Have you visited the newly renovated spartan club this semester?

2. Trying to learn

- Do you think the wait for food is longer than last semester with the new GrubHub system?
- Do you think the new Grubhub system is confusing (this could be a scale from 1-10)
- If it were up to you, would you keep the current system or revert back to last semester's?
- **I think we could use one more question for this but I'm not sure what. Maybe a short answer about the respondant's experience with the new spartan club? lmk thoughts **

3. The why

- Does the new system discourage you from visiting the spartan club for food?
- Do you think the school had the best interest of the students in mind when implementing the change? (this one is kind of leading)
- Do you think the grubhub system should be implemented for all on-campus dining options?


4. I'm not really sure what the netpromoter thing means.

**Comment by shreeya-ut** [comment]
From what I remember,  Net promoter is the likelihood of you recommending someone else to try it. So a question on a scale of 1-10, How likely are you to recommend the Grubhub services to order food to someone else?

**Comment by ronanflanny** [comment]
Ok so the 1-10 could just be "How likely are you to support the expansion of the grubhub system"

**Comment by Alessiox02** [comment]
How do you think the new system impacts non students trying to eat on campus?

**Comment by Alessiox02** [comment]
Also could include a question about which meal plan they have but not sure how and if that would help

**Comment by ronanflanny** [comment]
https://utampa.az1.qualtrics.com/jfe/form/SV_2n2Pgyt1BcLnQBE
