### ISSUE TITLE
Distribute the survey to at least 10 people

### ISSUE THREAD

**Issue by Justin-Tomasina** [Justin-Tomasina/QMB-210-5-group-3#2]
After you have distributed the survey to at least 10 people comment that you have.
Link for survey:
https://utampa.az1.qualtrics.com/jfe/form/SV_2n2Pgyt1BcLnQBE

**Comment by sophia-gorski** [comment]
completed!

**Comment by Tylershea5** [comment]
Completed

**Comment by mcane-ut** [comment]
Completed

**Comment by coopersharp2** [comment]
Completed

**Comment by shreeya-ut** [comment]
Completed, also shared amongst 2 organizations I am in.

**Comment by laurenschmidtt** [comment]
completed

**Comment by todrobina-ut** [comment]
completed

**Comment by ronanflanny** [comment]
completed

**Comment by DylanHilsheimer** [comment]
completed

**Comment by Alessiox02** [comment]
completed
