### ISSUE TITLE
First Data Pass

### ISSUE THREAD

**Issue by Justin-Tomasina** [Justin-Tomasina/QMB-210-5-group-3#3]
Create charts/ tables for the data from the survey.
Notes:
1. Who who, what what, and why why question pairs should be charts like a pie chart, bar chart, etc. (2 charts)
2. Who what and who why question pairs should be compiled into a pivot table or similar style data set. (1 table)
3. All work should be done on the shared file that everyone has access to, shared by Shreeya, this file will also include all of the data from the survey.
4. Attached is a list of what questions everyone should be analyzing.
5. Contact me over any concerns.
![Screenshot 2024-09-26 165428](https://github.com/user-attachments/assets/26c76ab1-164c-47af-8e23-0872ca8ec8b7)

**Comment by shreeya-ut** [comment]
I have emailed everyone the link to the shared excel document. Link: https://1drv.ms/x/c/e5886259026105ad/EXiWXQqYvq1Pl1OKUGw8AVgB0kRG8merPVh0j0lTktOvjQ?e=yLnihD
